var commentsArray = [

    {
       "id": 1,
       "parent": null,
       "created": "2021-11-15",
       "modified": "2021-11-15",
       "title": "𝗔𝗽𝗽𝗲𝗮𝗿𝘀 𝘁𝗼 𝘄𝗼𝗿𝗸",
       
      "content": "I've tried these a few times and they do seem to work. I definitely feel as though I sweat a lot more on runs when I'm on these than when I'm not and the weight does drop at the same time. I've just ordered my 3rd bottle so I guess that means I believe it's not all psychosomatic 🤷‍♂️",
       "attachments": [],
       "pings": [],
        "page": 2,
       "creator": 1,
       "fullname": "Khadija",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 10,
    
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 2,
       "parent": null,
       "created": "2021-11-08",
       "modified": "2021-11-08",
       "title": "𝗕𝗲𝘀𝘁 𝗻𝗼𝗻 𝘀𝘁𝗶𝗺 𝗳𝗮𝘁 𝗯𝘂𝗿𝗻𝗲𝗿!",
       
"content": "Absolutely love this product. I'm a long time fat burner user. Queen Formula is the best stimulent free fat burner I've tried and is priced competitively considering it's great well known proven ingredients. Curbs my appetite and great for weight management and metabolism.",
       "attachments": [],
       "pings": [],
    "page": 1,
       "creator": 1,
       "fullname": "Alicia M",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 2,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 3,
       "parent": null,
       "created": "2021-10-27",
       "modified": "2021-10-27",
       "title": "𝗦𝗽𝗲𝗲𝗱 𝘂𝗽 𝘆𝗼𝘂𝗿 𝗴𝗼𝗮𝗹𝘀!",
     
"content": "Its been around a month now since I have been using Queen Formula. It's a great product for weight loss. After consuming it for few 4-5 days I started to feel its effects. I helped me suppressing my hunger. It works amazingly especially if using Kaiser Coach. The best thing is that I don't see any side effects of the product and its all-natural. It definitely helps you reach ur goals quickly.",
       "attachments": [],
       "pings": [],
    "page": 1,
       "creator": 1,
       "fullname": "Nadia Johnston",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 4,
       "parent": null,
       "created": "2021-10-23",
       "modified": "2021-10-23",
       "title": "𝗦𝗵𝗼𝘂𝗹𝗱 𝘁𝗿𝘆 𝗶𝘁 !!!! 𝗚𝗼𝗼𝗱 𝗿𝗲𝘀𝘂𝗹𝘁𝘀",
       
"content": "Its really amazing and i have lost almost 5kgs in 4 weeks and you can feel those fat burning as energy and finally my appetite got controlled.. should try this product for sure...also my metabolism is beeb good .. I’m going continue it for four more week.. if you want the safe fat burner without any stimulant , just close your eyes and go for guys!!!!",
       "attachments": [],
       "pings": [],
    "page": 1,
       "creator": 1,
       "fullname": "Halima",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 6,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 5,
       "parent": null,
       "created": "2021-10-16",
       "modified": "2021-10-16",
       "title": "𝗚𝗿𝗲𝗮𝘁 𝗽𝗿𝗼𝗱𝘂𝗰𝘁 ",
      
"content": "This helps me to stop snacking between meals & makes it easier to skip meals/fast. I do feel fuller on a much smaller portion, than just one month ago. Unsure of the weight loss benefits (its still early days).",
       "attachments": [],
       "pings": [],
    "page": 1,
       "creator": 1,
       "fullname": "Chantelle. S",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 2,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 6,
       "parent": null,
       "created": "2021-10-09",
       "modified": "2021-10-09",
       "title": "𝗪𝗼𝗿𝗸𝘀 𝗚𝗿𝗲𝗮𝘁!",
      
"content": "I have been using Queen Formula for two months now. I use it for appetite control and weight management. My appetite has decreased so I eat in moderation and the increase In metabolism has helped with the weight loss 😃",       "attachments": [],
       "pings": [],
    "page": 1,
       "creator": 1,
       "fullname": "Tia L.",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 5,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    
    {
       "id": 8,
       "parent": null,
       "created": "2021-09-28",
       "modified": "2021-09-28",
       "title": "H𝗲𝗹𝗽𝗶𝗻𝗴 𝘄𝗶𝘁𝗵 𝗺𝘆 𝗔𝗽𝗽𝗲𝘁𝗶𝘁𝗲 𝗰𝗼𝗻𝘁𝗿𝗼𝗹",
"content": "Have been using Queen Formula for four weeks now and it has been helping with my Appetite control. I typically have strong cravings between meals but have noticed the urge to snack is less now.",
       "attachments": [],
       "pings": [],
    "page": 2,
       "creator": 1,
       "fullname": "Jess Flynn",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 5,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    
    {
       "id": 10,
       "parent": null,
       "created": "2021-09-17",
       "modified": "2021-09-17",
       "title": "𝗚𝗿𝗲𝗮𝘁 𝗽𝗿𝗼𝗱𝘂𝗰𝘁 𝘁𝗼 𝗸𝗶𝗰𝗸 𝘀𝘁𝗮𝗿𝘁 𝘄𝗲𝗶𝗴𝗵𝘁 𝗹𝗼𝘀𝘀",
"content": " Highly recommend trying out Queen Formula. As its a non stimulant it is great for kick starting weight loss without making you feel edgy. Happy i tried it and will continue using it",
       "attachments": [],
       "pings": [],
    "page": 1,
       "creator": 1,
       "fullname": "Christine",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 11,
       "parent": null,
       "created": "2021-09-09",
       "modified": "2021-09-09",
       "title": "𝗩𝗲𝗿𝘆 𝗦𝗮𝘁𝗶𝘀𝗳𝗶𝗲𝗱",
"content": "Very Happy with the product, curbed the appetite, boosted mood and energy and no ill effects. No complaints to be had at all. Shipped very very quickly on top of that!",
       "attachments": [],
       "pings": [],
    "page": 2,
       "creator": 1,
       "fullname": "Karen Wallace",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 12,
       "parent": null,
       "created": "2021-08-24",
       "modified": "2021-08-24",
       "title": "𝗟𝗼𝘃𝗲 𝘁𝗵𝗶𝘀 𝗽𝗿𝗼𝗱𝘂𝗰𝘁",
"content": "I have been using this product for a little over a month now and have been seeing great results. Reduces my appetite and increases fat burn. Will be ordering again",
       "attachments": [],
       "pings": [],
    "page": 2,
       "creator": 1,
       "fullname": "Hayley",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 0,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 13,
       "parent": null,
       "created": "2021-08-13",
       "modified": "2021-08-13",
       "title": "𝗜’𝘃𝗲 𝗔𝗹𝗿𝗲𝗮𝗱𝘆 𝘀𝗲𝗲𝗻 𝘁𝗵𝗲 𝗿𝗲𝘀𝘂𝗹𝘁",
"content": "Really useful in reducing hunger and appetite. I started to use it 10 days ago and easily could control my calorie intake...",
       "attachments": [],
       "pings": [],
    "page": 2,
       "creator": 1,
       "fullname": "Alice. M",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 6,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 14,
       "parent": null,
       "created": "2021-08-02",
       "modified": "2021-08-02",
       "title": "𝗚𝗼𝗼𝗱 𝗽𝗿𝗼𝗱𝘂𝗰𝘁 𝘄𝗶𝘁𝗵𝗼𝘂𝘁 𝗵𝗮𝗿𝗺𝗳𝘂𝗹 𝗳𝗶𝗹𝗹𝗲𝗿𝘀",
"content": "Good product. I’ve only been using it for a few weeks but seeing some great results so far.",
       "attachments": [],
       "pings": [],
    "page": 2,
       "creator": 1,
       "fullname": "Tara. H",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 15,
       "parent": null,
       "created": "2021-07-26",
       "modified": "2021-07-26",
       "title": "𝗛𝗶𝗴𝗵𝗹𝘆 𝗿𝗲𝗰𝗼𝗺𝗺𝗲𝗻𝗱",
        "content": "Great product! Takes away cravings, improves metabolism, and increases energy!",
       "attachments": [],
       "pings": [],
    "page": 3,
       "creator": 1,
       "fullname": "Holly Fleming",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 16,
       "parent": null,
       "created": "2021-07-19",
       "modified": "2021-07-19",
       "title": "𝗟𝗼𝘃𝗲 𝗶𝘁!",
        "content": " Great effective product! Highly recommend",
       "attachments": [],
       "pings": [],
        "page": 3,
       "creator": 1,
       "fullname": "Alicia",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 2,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 17,
       "parent": null,
       "created": "2021-07-11",
       "modified": "2021-07-11",
       "title": "𝗔𝗺𝗮𝘇𝗶𝗻𝗴",
"content": "This really helped. Really did a good job at stopping the munchies!",
       "attachments": [],
       "pings": [],
    "page": 3,
       "creator": 1,
       "fullname": "Hazel A.",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 3,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 18,
       "parent": null,
       "created": "2021-07-03",
       "modified": "2021-07-03",
       "title": "𝗟𝗲𝗮𝗻 𝗠𝗼𝗱𝗲!",
        "content": "I've been using the product for a couple of weeks and have found that the most evident thing, is my appetite has been suppressed, enabling my to eat that bit less and be more concious of my food intake, as I am working to lean down for my wedding in late June."+
       "<br><br> I've already lost 2.5kgs (was 106kg) so it’s definitely working for me so far.I would certainly recommend this product to anyone that is looking for support on weight management. As we all know diet is the highest contributor, quality products such as this, are great aids to keep the cogs moving, with metabolism, appetite and other factors!",
       "attachments": [],
       "pings": [],
    "page": 3,
       "creator": 1,
       "fullname": "Monica Sanders",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 8,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 19,
       "parent": null,
       "created": "2021-06-02",
       "modified": "2021-06-02",
       "title": "𝗦𝗼 𝗳𝗮𝗿 𝘀𝗼 𝗴𝗼𝗼𝗱 🙂",
        "content": "So far so good, have curbed my appetite, good packaging & quick delivery. Thank you!",
       "attachments": [],
       "pings": [],
    "page": 3,
       "creator": 1,
       "fullname": "Sharon",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 8,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 20,
       "parent": null,
       "created": "2021-05-24",
       "modified": "2021-05-24",
       "title": "𝗩𝗲𝗿𝘆 𝗲𝗳𝗳𝗲𝗰𝘁𝗶𝘃𝗲",
"content": "This stuff works. I was on a fat loss challenge and my body wouldn't play ball despite I worked out like crazy and counted macros. I was on these for 2 weeks and it provided the extra boost I needed. I took them whilst on a 9 day holiday in Asia. After the break, and the humidity/heat bloat subsided back home, I weighed myself and had lost a kg despite I only hit the gym once, ate what I wanted and had been drinking alcohol.",
       "attachments": [],
       "pings": [],
    "page": 3,
       "creator": 1,
       "fullname": "Ayla Rodriguez",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 5,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 21,
       "parent": null,
       "created": "2021-05-17",
       "modified": "2021-05-17",
       "title": "𝗧𝗵𝗲 𝗯𝗲𝘀𝘁 𝗶 𝗵𝗮𝘃𝗲 𝘂𝘀𝗲𝗱",
"content": "This is by far the best weight loss supplement i have ever used, i started using this product only 4 days ago and in them 4 days i managed to shed 9 pounds of body weight. What a fantastic product, will definitely be buying a few more bottles of these to my collection.",
       "attachments": [],
       "pings": [],
    "page": 4,
       "creator": 1,
       "fullname": "Janet. H",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 7,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 22,
       "parent": null,
       "created": "2021-05-11",
       "modified": "2021-05-11",
       "title": "𝗚𝗿𝗲𝗮𝘁 𝗽𝗿𝗼𝗱𝘂𝗰𝘁.",
"content": "After two months of taking Queen Formula, I look a lot slimmer, leanner and lighter.",
       "attachments": [],
       "pings": [],
    "page": 4,
       "creator": 1,
       "fullname": "Jennifer",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 1,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 23,
       "parent": null,
       "created": "2021-05-08",
       "modified": "2021-05-08",
       "title": "𝗣𝗹𝗲𝗮𝘀𝗲𝗱 𝘀𝗼 𝗳𝗮𝗿!",
"content": "I thought Queen Formula was reasonably priced and arrived quickly. I took it before breakfast and again before dinner. I found I ate less or was more satisfied with my meal and did not snack in-between meals. I have managed to keep my weight down despite being in lockdown with little access to training and stuck at home with temptations of snacking out of boredom. I will definitely be buying these again and look forward to seeing how they contribute to my diet once back in full training mode.",
       "attachments": [],
       "pings": [],
    "page": 4,
       "creator": 1,
       "fullname": "Ellen Carter",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 9,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 24,
       "parent": null,
       "created": "2021-05-02",
       "modified": "2021-05-02",
       "title": "𝗕𝗼𝗱𝘆 𝗳𝗮𝘁’𝘀 𝘄𝗼𝗿𝘀𝘁 𝗻𝗶𝗴𝗵𝘁𝗺𝗮𝗿𝗲",
"content": "When I began my journey with gym, I had a layer of fat that I have accumulated, and that I needed to burn off."+
       "<br><br> When searching numerous forums, I have frequently stumbled upon products made by KaiserFit, which have been recommended time and time again. That’s how I have discovered Queen Formula."+
       "<br><br> Thanks to this supplement, I have always been able to boost my metabolism and manage my weight. Any time I have slipped a little too much, I would go back to it and supplement my workout routine with this product and it worked!",
       "attachments": [],
       "pings": [],
    "page": 4,
       "creator": 1,
       "fullname": "Carla R.",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 13,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 25,
       "parent": null,
       "created": "2021-04-30",
       "modified": "2021-04-30",
       "title": "𝗣𝗲𝗿𝗳𝗲𝗰𝘁",
"content": "Lost some weight with these without going to the gym, great if you don't like stimulants..",
       "attachments": [],
       "pings": [],
    "page": 5,
       "creator": 1,
       "fullname": "Sue",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 7,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 26,
       "parent": null,
       "created": "2021-04-20",
       "modified": "2021-04-20",
       "title": "𝗪𝗶𝗹𝗹 𝗯𝘂𝘆 𝗮𝗴𝗮𝗶𝗻",
"content": "I'm 3/4 of the way through my first bottle, I dont weigh myself but ive lost 6 inches in 6 weeks, ive taken before and after photos and the difference is noticeable already. My energy levels are amazing, im working out 1-2 times daily as i feel motivated and energetic all of the time."+
       "<br><br> They also really help my digestion, i never feel bloated anymore, its really regulated my system."+
       "<br><br> I'll be purchasing another bottle and people have already asked me whats my secret!",
       "attachments": [],
       "pings": [],
    "page": 5,
       "creator": 1,
       "fullname": "Aimee. B",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 10,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 27,
       "parent": null,
       "created": "2021-04-14",
       "modified": "2021-04-14",
       "title": "𝗔𝗰𝘁𝘂𝗮𝗹𝗹𝘆 𝗱𝗼 𝘄𝗼𝗿𝗸",
"content": "I actually ordered this because of the good reviews. To be honest I was quite skeptical as most diet pills do next to nothing but these actually do work well, if used with the right protocol of course. <br><br>"+
       "I have been dieting for a few months and hit a bit of a plateau so started these. I'd say they definitely help with upping your metabolism as I started to lose 2lbs a week Vs 1lbs a week without changing my diet or exercise. I was amazed if I'm honest. <br><br>"+
       "Appetite control is there and it does help with binge eating, all in all a very good product.",
       "attachments": [],
       "pings": [],
    "page": 5,
       "creator": 1,
       "fullname": "Lauren Robbins",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 7,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    {
       "id": 28,
       "parent": null,
       "created": "2021-04-05",
       "modified": "2021-04-05",
       "title": "𝗔𝗺𝗮𝘇𝗶𝗻𝗴",
"content": "I have recently started using this product and I must say I am already very impressed. I have struggled recently to manage my weight but Queen Formula has played a massive part in helping me look slimmer. Every morning when I wake up I will have some Queen Formula and that helps to control my appetite and leaves me feeling fuller for longer. I also feel that while taking Queen Formula my metabolism seems to have improved which is something I have struggled with for a long time. Overall I am very happy with this product, and will continue to use it in the future.",
       "attachments": [],
       "pings": [],
        "page": 5,
       "creator": 1,
       "fullname": "Erika",
       "profile_picture_url": "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png",
       "created_by_admin": false,
       "created_by_current_user": false,
       "upvote_count": 2,
       "user_has_upvoted": false,
       "is_new": false
    },
    
    ]
    
    var usersArray = [
       {
          id: 1,
          fullname: "Current User",
          email: "current.user@viima.com",
          profile_picture_url: "https://viima-app.s3.amazonaws.com/media/public/defaults/user-icon.png"
       },
   
    ]
    